version: "3.3"

services:

  app:
    #entrypoint: yarn dev:server
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3333:3333"
      - "9229:9229"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
